### PR TITLE
Colorgrid made responsive

### LINKED ISSUE #17: Responsiveness
* Website is not responsive. I would like to work on responsiveness.

### PR DESCRIPTION
**Pull request by Snehil0603**
# Fixes #17 
## Previously
p1
p2

## Color Grid has been made responsive
r1
r2

### CODE REVIEW

**Comment by SscSPs** [comment]
Hey @Snehil0603, the screenshots looks great!
Also, looks like there are some warnings, please fix them so we can go ahead and merge this

**Comment by SscSPs** [comment]
Awesome! Thanks for the changes!
One suggestion I have,instead of hard coding them to 3%, we should set it based on the saturationCount and luminosityCount variables, 
The logic can be that we allow 50% for the grid, and then we can use the saturationCount and luminosityCount to get the value by dividing 50 by them!

So, something like this: 
width = 50/saturationCount
Will that work?

**Comment by Snehil0603** [comment]
Previously the height and width was being set using saturationCount and luminosityCount but it led to grid being un responsive that is why I set it to values .So it was not really working that way

**Comment by SscSPs** [comment]
Earlier, there were 2 datapoint being used, one was window's hight and width, and saturationCount and luminosityCount.
Now you have removed both of them, and hard set it to 3% of window's hight and width,
what I'm suggesting is to use 50(try a few different values, 60 or 70) instead of window hight/width, and use the resulting value as the size for cell in vh/vw, 
see if this works, I think it should work this way.

The reason I'm asking this is because there's another PR that adds support for modifying the count using a slider available to user, if we make this hard coded to 3, then changing the count may result in overflowing the cells form visible screen.

**Comment by Snehil0603** [comment]
@SscSPs please kindly check this pr now

**Pull request closed without merging**
