### PR TITLE
Updated content Readme.md. Close #51

### LINKED ISSUE #51: Readme link live project
It would be nice to open a new browser tab when clicking on live project, so the user wouldn't leave your project on github. If that makes sense to you, you can assign me that adjustment. Thanks.

### PR DESCRIPTION
**Pull request by BrunoLagoa**
@SscSPs 
I made some adjustments to Readme.
  - Added a splash image
  - Added link to doc in ReactJS

I hope you enjoy.

### CODE REVIEW

**Comment by BrunoLagoa** [comment]
If possible, would you like to add the tags to this pr, hacktoberfest, hacktoberfest-accepted. to participate in the event.

**Comment by SscSPs** [comment]
Hey, Thanks for the PR, looks good, 
Just one thing, the desktop mockup is cropped, can you align the image better so the bottom and left margins(of the app) are also visible?

**Comment by SscSPs** [comment]
and about the labels, read #47

**Comment by BrunoLagoa** [comment]
@SscSPs  Hi, updated image.

**Comment by SscSPs** [comment]
Thanks for updating the mockup, I just noticed that you added the mockup in the public dir, 
public dir is built into the app, and we don't need this in the app, so I think it will be better if we put it in some other directory, "assets" can work, or "images" 
this directory should be in the root of the repo,

**Comment by BrunoLagoa** [comment]
I added it to public, it was the only place I saw the image, we can move it to assets without any problems, src/assets ?

**Comment by BrunoLagoa** [comment]
updated pr

**Comment by SscSPs** [comment]
Hey, sorry i didn't reply earlier, 
I actually meant creating new directory, assets sibling to src, not the one inside src,
Or, "images" sibling to src,

I understand the confusion for using public, the thing is, "public" is a special directory which is bundled into the app, we don't need this image in the app, so we shouldn't add it to the bundle and increase the side needlessly. That's the reason I asked you to move it out.
Same is the case with src, we should not add non essential files/blobs/directory in these 2 directories, we can create any other folder outside of these 2 for non app essential things!

I hope this makes sense, let me know if you have any questions

**Comment by BrunoLagoa** [comment]
Nice! good explanation. I will update the pr again. LOL

**Comment by BrunoLagoa** [comment]
up

**Comment by SscSPs** [comment]
Awesome! Looks great! Thanks for the efforts! 👍

**Comment by BrunoLagoa** [comment]
If possible, would you like to add the tags to this pr, hacktoberfest, hacktoberfest-accepted. to participate in the event.

**Comment by SscSPs** [comment]
About hacktoberfest, #47

**Comment by BrunoLagoa** [comment]
You don't need to worry about hacktoberfest-accepted label on your PR, the repo itself have the label, so all your PRs will show up on your dashboard in about 30 minutes of your refresh.

nice!

**Pull request merged**
