### PR TITLE
CSS styling

### PR DESCRIPTION
**Pull request by sauravsilawat**
I Beautified it, hope you like it.
 

please merge it under Hactoberfest  tag

### CODE REVIEW

**Comment by SscSPs** [comment]
Your design looks awesome, but looks like you've mistakenly put your modified files in wrong place, please update the paths to match where they currently are, which is ./src

**Comment by sauravsilawat** [comment]
Updated, 
I have a question will it be counted for the hactoberfest contribution?

**Comment by SscSPs** [comment]
Changes looks good, will merge soon, 
And yes, This PR will reflect on your hacktoberfest dashboard soon(if not already)

**Comment by sauravsilawat** [comment]
Thank you.

**Comment by SscSPs** [comment]
Hey @sauravsilawat would it be okay with you if this image were to be used in the README? the readme will look better if there are some images in it and this looks good

**Comment by sauravsilawat** [comment]
Yes, why not.

**Pull request merged**
