### PR TITLE
Made necessary changes to the README setup

### PR DESCRIPTION
**Pull request by PiXeL99-eng**
The application will not start if we don't install the necessary npm packages, mentioned in the package.json. Hence updated the read me with the instruction to use "npm install" to install the required npm packages #1

### CODE REVIEW

**Comment by SscSPs** [comment]
Hi, Thanks for the PR, looks good to me!

**Comment by PiXeL99-eng** [comment]
Can u give "hacktober-fest accepted" tag to this PR?

**Comment by SscSPs** [comment]
The Repo contains the label, so the PR doesn't need it.
You should be able to see the PR show up on your hacktoberfest dashboard soon(if not already)

**Comment by PiXeL99-eng** [comment]
Yes, it did. Thanks for the info.

**Pull request merged**
