### PR TITLE
Add a text header for making the app more user friendly 

### PR DESCRIPTION
**Pull request by smiti-maheshwari**
This is updating README.md regarding the issue https://github.com/SscSPs/color/issues/1. This is for [Hacktoberfest2022](https://github.com/topics/hacktoberfest).

### CODE REVIEW

**Comment by SscSPs** [comment]
Hi @smiti-maheshwari 
Thanks for you PR, but this doesn't look good in the place you added it 😅

You can try adding that line above or even better if you can add it on the app Page itself, like a header above the content, or may be above the color picker!

**Comment by smiti-maheshwari** [comment]
Hey @SscSPs!
By content, do you mean the entire palette or just above the frame where we can choose the colours?

**Comment by SscSPs** [comment]
Both are good options, you can put it in either place as you see fit 😄

**Comment by smiti-maheshwari** [comment]
How does this screenshot look @SscSPs? I have added Choose a color just above the frame where we pick the colours. Also I have changed the content of header instead of "Color" to "Color Picker" because that seems better. 

Screenshot 2022-10-09 at 1 34 19 PM

Let me know if this seems okay or somethings needs to be changed.

**Comment by SscSPs** [comment]
Looks good, push the changes and I'll merge

**Comment by smiti-maheshwari** [comment]
Cool, thanks!

**Pull request merged**
